### PR TITLE
Add option to pass custom DB session on method call

### PR DESCRIPTION
**Pull request by asafalima**
We use it to pass the active transaction to authority when updating our users.
I've added a test that check this functionality.

### CODE REVIEW

**Comment by asafalima** [comment]
@harranali Can you please take a look at this change and at #8?
Thanks

**Comment by asafalima** [comment]
@harranali What do you think about this change?
Also we need to merge #8 for users to be able to install and use this package correctly

**Comment by asafalima** [comment]
Hi @harranali, Can we please push this change?

**Comment by asafalima** [comment]
Hi @harranali, I would really like us to merge this PR alongside https://github.com/harranali/authority/pull/8
We use this fork for a while now in production and we want to use the upstream.

Thank you

**Comment by harranali** [comment]
Hi @asafalima ,
I have just added transactions with a simpler approach by adding 3 functions `BeginTX`, `Rollback()`, and `Commit()`,
for more info please refer to the [develop](https://github.com/harranali/authority/tree/develop) branch code and the readme file.
Thanks.

**Pull request closed without merging**
